# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: MIT

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-16.5

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    0cc70793711af3a1cf65ec0fac2a2c147695c1d3 # master
  subdirs:
    - code/cleveland
    - code/morley-client

- git:
    https://gitlab.com/morley-framework/morley-metadata.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    34342cf86e51190b541a68f795899a4328a3db01 # master
  subdirs:
    - code/morley-metadata
    - code/morley-metadata-test

# Stable parts of morley available from Hackage
- morley-1.12.0
- morley-prelude-0.3.0
- lorentz-0.9.1
- indigo-0.5.0

# Required by morley
- tasty-hunit-compat-0.2
- uncaught-exception-0.1.0
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- base-noprelude-4.13.0.0@sha256:3cccbfda38e1422ca5cc436d58858ba51ff9114d2ed87915a6569be11e4e5a90,6842
- fmt-0.6.1.2@sha256:405a1bfc0ba0fd99f6eb1ee71f100045223f79204f961593012f28fd99cd1237,5319
- named-0.3.0.1@sha256:69b9722301201f8ed8abc89c4595e22c746e944bf4cdfafa8b21b14d336b26d1,2233
- vinyl-0.12.1@sha256:43456d4b3009646eee63953cbe539f1f4d0caf8bc3c25e841117e712836508f3,3790
- cryptonite-0.27

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    f4e3fffca1d877e404b38c54d8e1b411641c3548 # master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test
